print('Hello my dear friend,')
print('I would like to ask you something, \nwhat is your favorite color?')
Name = input('Please type your favorite color:')
print('Your favorite color is')
print(Name)
print('That is a great choice \nCongratulations!')
print('Ey, I have another question for you, what is your second favorite color?') 
Name = input ('Please type your second favorite color:')
print('Your second favorite color is')
print(Name)
print('Very good my friend!')